export default Object.freeze({
  ADD_ANNOUNCEMENT: 'ADD_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
  EDIT_ANNOUNCEMENT: 'EDIT_ANNOUNCEMENT',
  SEARCH_ANNOUNCEMENT: 'SEARCH_ANNOUNCEMENT',
  CURRENT_ANNOUNCEMENT_ID: 'CURRENT_ANNOUNCEMENT_ID',
});
